---
title: "Lecture 0"
author: "Jorge Luis Ojeda Cabrera & Bruno Contreras Moreira"
date: '`r format(Sys.Date(),"%d/%b/%Y")`'
output:
  html_document:
    fig_caption: yes
    highlight: zenburn
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
  ioslides_presentation:
    css: ../comm/bkgr.css
    fig_caption: yes
    incremental: yes
    logo: ../comm/quantBiotech.png
    smaller: yes
    toc: yes
    toc_depth: 3
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 3
  slidy_presentation:
    incremental: yes
  word_document: default
geometry: margin=1cm
fontsize: 11pt
---



```{r setup, include=FALSE}
comm<-list(
  ASIGNATURA="Biostatistics & Bioinformatics Methods</p>Máster en Biotecnología Cuantitativa",
  DATE=format(Sys.Date(),"%d/%b/%Y"),           ## "Dic. 2016",
  PROFESOR="[Jorge Luis Ojeda Cabrera](http://metodosestadisticos.unizar.es/personales/jojeda) (<jojeda@unizar.es>)",
  TUTORIAS="Edif. Matemáticas (Fac. Ciencias), Dept. Métodos Estadísticos(3rd floor), room. Num. 8.\n
    + Mondays 10:30 till 12:30 and 1530 till 1730, y Thursday 10:30 till 12:30.\n
    + I use to be in my room almost all mornings.\n
    + I _will try to be_ in the lab room half an hour before schedule.\n
    + Use mail to schedule a tutorship out of the tutorship timetable.\n"
)


## Some interesting settings
library(knitr)
library(ggplot2)
library(gridExtra)
library(xtable)
FIGSIZE<-3.5
knitr::opts_chunk$set(echo=FALSE, fig.height=FIGSIZE, fig.width=2*FIGSIZE)

```


\newcommand{\ol}[1]{\overline{#1}}
\newcommand{\ul}[1]{\underline{#1}}
\newcommand{\myProb}[1]{ {\mathbf{P}\kern-2pt\left( #1 \right)} }
\newcommand{\myF}[2]{ {{#1}\kern-2pt\left( {#2} \right)} }
\newcommand{\mycp}[1]{ {\left(#1\right)} }
\newcommand{\EE}[1]{ {\mathbf{E}\left[ #1 \right]} }

# Introduction

```{r child="intro.Rmd"}
```


# Topics


## Statistical Toolbox Program

```{r child="statProg.Rmd"}
```


## Bioinformatics Program

```{r child="bioInfProg.Rmd"}
```


# The course

```{r child="asig.Rmd"}
```




<!--
Last compilation: `r format(Sys.Date(),"%d/%b/%Y")`
-->

